"""Recording and reading reviews."""

from typing import Annotated

from pydantic import BaseModel, Field

from ..sync.schemas import RowId, UtcDatetime

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200


class ReviewLogCreate(BaseModel):
    """One review that happened.

    The id is generated by the client, which is what makes recording a review
    idempotent: a retry after a dropped connection carries the same id and
    lands on the row already there instead of counting the review twice.

    The scheduling the client computed travels with it. The server does not
    re-run the algorithm — it stores what the client decided and applies it to
    the entry under the same rule sync uses, so a review recorded here and one
    pushed through sync are indistinguishable afterwards.
    """

    id: RowId
    glossary_entry_id: RowId
    reviewed_at: UtcDatetime
    grade: Annotated[int, Field(ge=0, le=5)]
    scheduled_interval_days: Annotated[int, Field(ge=0, le=3650)]
    scheduled_ease_factor: Annotated[float, Field(ge=1.3, le=5.0)]


class ReviewLogView(BaseModel):
    id: str
    glossary_entry_id: str
    reviewed_at: UtcDatetime
    grade: int
    scheduled_interval_days: int
    scheduled_ease_factor: float
    updated_at: UtcDatetime


class ReviewLogPage(BaseModel):
    reviews: list[ReviewLogView]


class RecordedReview(BaseModel):
    """What recording a review did.

    [applied] is false when the review was already known — a retry — or when
    the entry had a more recent review from another device, in which case the
    log is kept but the schedule is not moved backwards.
    """

    review: ReviewLogView
    applied: bool
    entry_interval_days: int
    entry_ease_factor: float
    entry_due_at: UtcDatetime | None
